<x-app-layout>
    @php
        $formatMb = fn (?int $value) => $value === null ? 'Tidak tersedia' : number_format($value, 0, ',', '.').' MB';
        $usage = fn (?int $used, ?int $limit) => $used === null ? 'Tidak tersedia' : number_format($used, 0, ',', '.').' MB'.($limit !== null && $limit > 0 ? ' / '.number_format($limit, 0, ',', '.').' MB' : ' / Tidak dibatasi');
    @endphp

    <div class="space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
                <a href="{{ route('servers.users', $server) }}" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-blue-600 dark:text-slate-400 dark:hover:text-blue-300"><i data-lucide="arrow-left" class="h-4 w-4"></i>Kembali ke Daftar User</a>
                <div class="mt-3 flex flex-wrap items-center gap-3">
                    <h1 class="text-2xl font-bold text-slate-800 dark:text-white">{{ $user['username'] }}</h1>
                    <span class="inline-flex items-center rounded-full px-2.5 py-1 text-xs font-bold {{ $user['suspended'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' }}">{{ $user['suspended'] ? 'Suspended' : 'Aktif' }}</span>
                    @if($hosting)
                        <span class="inline-flex items-center rounded-full bg-blue-100 px-2.5 py-1 text-xs font-bold text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">{{ $hosting->managed_by_crm ? 'Dikelola CRM' : 'Read-only' }}</span>
                    @endif
                </div>
                <p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Detail penggunaan resource dibaca dari HestiaCP dan di-cache selama 2 menit.</p>
            </div>
            <a href="{{ route('servers.users.show', ['server' => $server, 'username' => $user['username'], 'refresh' => 1]) }}" class="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 transition hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"><i data-lucide="refresh-cw" class="h-4 w-4"></i>Refresh Data</a>
        </div>

        @foreach($warnings as $warning)
            <div class="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-800 dark:bg-amber-900/20 dark:text-amber-300">{{ $warning }}</div>
        @endforeach

        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Disk Space</p><p class="mt-2 text-lg font-bold text-slate-800 dark:text-white">{{ $usage($user['disk_used_mb'], $user['disk_quota_mb']) }}</p><div class="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-700">@if(($user['disk_quota_mb'] ?? 0) > 0)<div class="h-full rounded-full {{ $user['disk_used_mb'] > $user['disk_quota_mb'] ? 'bg-red-500' : 'bg-blue-500' }}" style="width: {{ min(100, (int) round((($user['disk_used_mb'] ?? 0) / $user['disk_quota_mb']) * 100)) }}%"></div>@endif</div></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Bandwidth</p><p class="mt-2 text-lg font-bold text-slate-800 dark:text-white">{{ $usage($user['bandwidth_used_mb'], $user['bandwidth_quota_mb']) }}</p><p class="mt-2 text-xs text-slate-500 dark:text-slate-400">Akumulasi sesuai periode HestiaCP.</p></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Database</p><p class="mt-2 text-lg font-bold text-slate-800 dark:text-white">{{ $user['databases_count'] ?? 'Tidak tersedia' }}{{ ($user['databases_limit'] ?? 0) > 0 ? ' / '.$user['databases_limit'] : '' }}</p><p class="mt-2 text-xs text-slate-500 dark:text-slate-400">{{ count($databases) }} detail database dapat dibaca.</p></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Web Domain</p><p class="mt-2 text-lg font-bold text-slate-800 dark:text-white">{{ $user['web_domains_count'] ?? 'Tidak tersedia' }}{{ ($user['web_domains_limit'] ?? 0) > 0 ? ' / '.$user['web_domains_limit'] : '' }}</p><p class="mt-2 text-xs text-slate-500 dark:text-slate-400">{{ count($webDomains) }} domain terdeteksi.</p></section>
        </div>

        <div class="grid gap-6 xl:grid-cols-3">
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2 dark:border-slate-700 dark:bg-slate-800">
                <div class="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><h2 class="font-bold text-slate-800 dark:text-white">Rincian Pemakaian Disk</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Nilai dari pencatatan pemakaian HestiaCP dalam MB.</p></div>
                <dl class="grid gap-x-6 gap-y-5 p-6 sm:grid-cols-2">
                    <div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Web</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $formatMb($user['disk_web_mb']) }}</dd></div>
                    <div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Mail</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $formatMb($user['disk_mail_mb']) }}</dd></div>
                    <div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Database</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $formatMb($user['disk_database_mb']) }}</dd></div>
                    <div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Total Direktori</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $formatMb($user['disk_used_mb']) }}</dd></div>
                </dl>
            </section>
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><h2 class="font-bold text-slate-800 dark:text-white">Profil Akun</h2></div><dl class="space-y-4 p-6"><div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Nama</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $user['name'] ?: '-' }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Email Kontak</dt><dd class="mt-1 break-all text-sm text-slate-800 dark:text-slate-100">{{ $user['email'] ?: '-' }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Paket Hestia</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $user['package'] ?: '-' }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wide text-slate-400">Mail / Backup / Cron</dt><dd class="mt-1 font-semibold text-slate-800 dark:text-slate-100">{{ $user['mail_domains_count'] ?? '-' }} domain · {{ $user['mail_accounts_count'] ?? '-' }} akun · {{ $user['backups_count'] ?? '-' }} backup · {{ $user['cron_jobs_count'] ?? '-' }} cron</dd></div></dl></section>
        </div>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><h2 class="font-bold text-slate-800 dark:text-white">Database</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Daftar read-only dari HestiaCP. Password database tidak pernah diambil atau ditampilkan.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm"><thead class="border-b border-slate-100 bg-slate-50/70 text-xs font-bold uppercase tracking-wide text-slate-400 dark:border-slate-700 dark:bg-slate-700/20"><tr><th class="px-6 py-3">Database</th><th class="px-6 py-3">User</th><th class="px-6 py-3">Host</th><th class="px-6 py-3">Engine</th><th class="px-6 py-3">Ukuran</th><th class="px-6 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($databases as $database)<tr class="hover:bg-slate-50 dark:hover:bg-slate-700/30"><td class="px-6 py-4 font-mono font-semibold text-slate-800 dark:text-slate-100">{{ $database['name'] }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $database['user'] ?: '-' }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $database['host'] ?: '-' }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $database['type'] ?: '-' }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $formatMb($database['disk_mb']) }}</td><td class="px-6 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $database['suspended'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' }}">{{ $database['suspended'] ? 'Suspended' : 'Aktif' }}</span></td></tr>@empty<tr><td colspan="6" class="px-6 py-10 text-center text-slate-500 dark:text-slate-400">Tidak ada detail database yang dapat dimuat.</td></tr>@endforelse</tbody></table></div></section>

        <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><div class="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><h2 class="font-bold text-slate-800 dark:text-white">Web Domain</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Penggunaan disk per domain, status SSL, dan status domain dari HestiaCP.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-sm"><thead class="border-b border-slate-100 bg-slate-50/70 text-xs font-bold uppercase tracking-wide text-slate-400 dark:border-slate-700 dark:bg-slate-700/20"><tr><th class="px-6 py-3">Domain</th><th class="px-6 py-3">Disk</th><th class="px-6 py-3">Bandwidth</th><th class="px-6 py-3">SSL</th><th class="px-6 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100 dark:divide-slate-700">@forelse($webDomains as $domain)<tr class="hover:bg-slate-50 dark:hover:bg-slate-700/30"><td class="px-6 py-4 font-mono font-semibold text-slate-800 dark:text-slate-100">{{ $domain['domain'] }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $formatMb($domain['disk_mb']) }}</td><td class="px-6 py-4 text-slate-700 dark:text-slate-300">{{ $formatMb($domain['bandwidth_mb']) }}</td><td class="px-6 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $domain['ssl'] ? 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300' }}">{{ $domain['ssl'] ? ($domain['lets_encrypt'] ? 'Let\'s Encrypt' : 'SSL Aktif') : 'Tidak aktif' }}</span></td><td class="px-6 py-4"><span class="inline-flex rounded-full px-2.5 py-1 text-xs font-bold {{ $domain['suspended'] ? 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300' : 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300' }}">{{ $domain['suspended'] ? 'Suspended' : 'Aktif' }}</span></td></tr>@empty<tr><td colspan="5" class="px-6 py-10 text-center text-slate-500 dark:text-slate-400">Tidak ada detail domain web yang dapat dimuat.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-app-layout>
