<?php

return [
    'queues' => [
        'noc' => 'NOC',
        'technical' => 'Technical Support',
        'billing' => 'Billing',
        'provisioning' => 'Provisioning',
        'general' => 'General Support',
    ],
    'placeholders' => [
        'client_name' => 'Nama pelanggan',
        'client_code' => 'Kode pelanggan',
        'branch_name' => 'Nama cabang pelanggan',
        'primary_contact_name' => 'Nama PIC utama',
        'primary_contact_phone' => 'Telepon PIC utama',
        'primary_contact_email' => 'Email PIC utama',
        'ticket_number' => 'Nomor ticket',
        'ticket_subject' => 'Subjek ticket',
        'ticket_category' => 'Kategori ticket',
        'ticket_priority' => 'Priority ticket',
        'ticket_status' => 'Status ticket',
        'queue_name' => 'Nama queue/department',
        'subscription_code' => 'Kode langganan',
        'package_name' => 'Nama paket langganan',
        'service_name' => 'Nama layanan',
        'installed_at' => 'Tanggal instalasi layanan',
        'next_billing_date' => 'Tanggal billing berikutnya',
        'effective_price' => 'Harga aktif langganan',
        'ip_address' => 'IP Address koneksi',
        'pppoe_user' => 'Username PPPoE',
        'router_model' => 'Model router/ONT',
        'metro_name' => 'Nama Metro Ethernet',
        'zabbix_host_name' => 'Host monitoring Zabbix',
    ],
    'category_queue_map' => [
        'connectivity' => 'noc',
        'technical' => 'technical',
        'billing' => 'billing',
        'general' => 'general',
    ],
];
